### PR TITLE
Allow CTRL-w to clear current word

### PR DESCRIPTION
**Pull request by afh**
this makes it easy to guess a new word especially when the current guess is invalid.

### CODE REVIEW

**Comment by afh** [comment]
Friendly ping on this, @conradludgate. Do you see value in the changes this PR brings?

**Review by conradludgate — APPROVED** [review]
Seems a bit redundant, but I have no real problems with it. What's the reasoning for CTRL-W?

**Comment by afh** [comment]
In shells CTRL-W is often mapped to the "delete word" command (see documentation for [Zsh Line Editor Modifying Text](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Modifying-Text) on `vi-backward-kill-word` and `backward-kill-word` for example).

**Comment by afh** [comment]
Thanks for merging this, @conradludgate.

**Pull request merged**
